version: '3'

services:
  mysql:
    image: mysql:5.5

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=demodemo

    volumes:
      - ./SQLScripts:/docker-entrypoint-initdb.d

    container_name: mysql